import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Undo2, Redo2 } from 'lucide-react';
import EnterpriseSitePlanner from '../../components/EnterpriseSitePlannerShell';
import { SitePlannerErrorBoundary } from '../../components/ErrorBoundary';
import type { InvestmentAnalysis, SelectedParcel } from '../../types/parcel';
import { createFallbackParcel, isValidParcel } from '../../types/parcel';
import { useBuildableEnvelope } from './api/useBuildableEnvelope';
import { useSitePlanState } from './state/useSitePlanState';
import { workerManager } from '../../workers/workerManager';
import type { Element, FeasibilityViolation } from '../../engine/types';
import type { EdgeClassification } from '../../engine/setbacks';
import { normalizeToPolygon, calculatePolygonCentroid, correctedAreaM2, buffer, intersection, polygons, areaM2 } from '../../engine/geometry';
import { feature4326To3857 } from '../../utils/reproject';
import { feetToMeters } from '../../engine/units';
import { typologyToBuildingType, generateDefaultUnitMix, generateUnitMixForCount, type BuildingSpec } from '../../engine/model';
import { placeBarsAlongEdges } from '../../engine/edgePlacement';
import { buildBuildingFootprint } from '../../engine/buildingGeometry';
import { computeProForma } from '../../engine/proforma';
import type { Polygon, MultiPolygon } from 'geojson';
import ParametersPanel from './ui/ParametersPanel';
import ResultsPanel from './ui/ResultsPanel';
import Massing3D from './ui/Massing3D';
import KpiStrip from './ui/KpiStrip';
import ContextPanel from './ui/ContextPanel';
import { contextToZoningPatch, isHorizontalRegime, type DesignContext } from './api/designContext';
import { generateSfSitePlan, sfPlanToElements } from './api/generateSfPlan';
import { useSitePlans } from '../../hooks/useSitePlans';
import type { SavedSitePlan } from '../../lib/sitePlanStorage';

type SiteWorkspaceProps = {
  parcel: SelectedParcel;
};

const SiteWorkspace: React.FC<SiteWorkspaceProps> = ({ parcel }) => {
  const {
    config,
    updateConfig,
    elements,
    metrics,
    setPlanOutput,
    alternatives,
    solveScores,
    selectedSolveIndex,
    selectedSolve,
    selectSolve,
    applyAlternatives,
    normalizedGeometry,
    isValidParcel: hasValidGeometry
  } = useSitePlanState(parcel);
  const { status, envelope, rpcMetrics, edgeClassifications, error: envelopeError } = useBuildableEnvelope(parcel);
  const [isGenerating, setIsGenerating] = useState(false);
  const [viewMode, setViewMode] = useState<'2d' | '3d'>('2d');
  const [violations, setViolations] = useState<FeasibilityViolation[]>([]);

  // ── Design-context engine (brief Phase 1) ────────────────────────────────
  const contextOgcFid = useMemo(() => {
    const n = Number(parcel.ogc_fid);
    return Number.isFinite(n) && n > 0 ? n : null;
  }, [parcel.ogc_fid]);
  const [contextUse, setContextUse] = useState('single_family');
  const appliedContextRef = useRef<string | null>(null);

  // ── SF lot generator (brief Phase 2) ─────────────────────────────────────
  const [isGeneratingLots, setIsGeneratingLots] = useState(false);
  const [lotFitSummary, setLotFitSummary] = useState<string | null>(null);

  // ── HBU / regime plan routing ─────────────────────────────────────────────
  // What we planned and WHY, shown under the KPI bar ("Plan basis: …").
  const [planBasis, setPlanBasis] = useState<string | null>(null);
  // 'sf' = lot generator drives the plan; 'mf' = massing engine. Guards the
  // live re-solver from painting multifamily apparatus over an SF lot fit.
  const planModeRef = useRef<'sf' | 'mf' | null>(null);
  const ctxSettledRef = useRef<DesignContext | null | 'pending'>('pending');

  // ── Undo / redo ───────────────────────────────────────────────────────────
  // The undo unit is the worker's canonical BuildingSpec[] — restoring a
  // snapshot replays it through the worker (SET_BUILDINGS) so parking, metrics
  // and pro forma all regenerate consistently. Max 50 steps.
  const currentBuildingsRef = useRef<BuildingSpec[]>([]);
  const pastRef = useRef<BuildingSpec[][]>([]);
  const futureRef = useRef<BuildingSpec[][]>([]);
  const gestureActiveRef = useRef(false);
  const [historyVersion, setHistoryVersion] = useState(0);

  const trackBuildings = useCallback((buildings?: BuildingSpec[]) => {
    if (buildings) currentBuildingsRef.current = buildings;
  }, []);

  const pushHistory = useCallback(() => {
    pastRef.current.push(structuredClone(currentBuildingsRef.current));
    if (pastRef.current.length > 50) pastRef.current.shift();
    futureRef.current = [];
    setHistoryVersion(v => v + 1);
  }, []);
  const [investmentAnalysis, setInvestmentAnalysis] = useState<InvestmentAnalysis | null>(null);
  const [solverReady, setSolverReady] = useState(false);
  const hasAutoGeneratedRef = useRef(false);
  const lastParcelIdRef = useRef<string | number | null>(null);

  // Plan persistence
  const parcelIdStr = String(parcel.ogc_fid ?? parcel.id ?? 'unknown');
  const {
    plans: savedPlans,
    isLoading: savedPlansLoading,
    error: savedPlansError,
    save: savePlanToDb,
    remove: deletePlanFromDb,
    setFavorite: togglePlanFavorite,
  } = useSitePlans(parcelIdStr);

  const handleSavePlan = useCallback(
    (name: string) => {
      savePlanToDb({
        parcel_id: parcelIdStr,
        name,
        config,
        elements,
        metrics,
        violations,
        investment: investmentAnalysis,
      });
    },
    [savePlanToDb, parcelIdStr, config, elements, metrics, violations, investmentAnalysis]
  );

  const handleLoadPlan = useCallback(
    (plan: SavedSitePlan) => {
      setPlanOutput(plan.elements ?? [], plan.metrics ?? null);
      setViolations(plan.violations ?? []);
      setInvestmentAnalysis(plan.investment ?? null);
    },
    [setPlanOutput]
  );

  const envelopeMeters = useMemo(() => {
    // Step 1: Get the parcel polygon in EPSG:3857 (needed for all paths)
    let parcelPoly3857: Polygon | null = null;
    try {
      if (parcel?.geometry) {
        const geom = parcel.geometry as Polygon | MultiPolygon;
        const coords = geom.type === 'Polygon' ? geom.coordinates[0] : geom.coordinates[0][0];
        const is3857 = Math.abs(coords?.[0]?.[0] ?? 0) > 1000 || Math.abs(coords?.[0]?.[1] ?? 0) > 1000;
        const reprojected = is3857 ? geom : (feature4326To3857(geom) as Polygon | MultiPolygon);
        parcelPoly3857 = normalizeToPolygon(reprojected);
      }
    } catch { /* parcel geometry is invalid */ }

    // Step 2: Try to use the RPC envelope
    let env: Polygon | null = null;
    if (envelope && status === 'ready') {
      try {
        const geom = envelope as Polygon | MultiPolygon;
        const coords = geom.type === 'Polygon' ? geom.coordinates[0] : geom.coordinates[0][0];
        const is3857 = Math.abs(coords?.[0]?.[0] ?? 0) > 1000 || Math.abs(coords?.[0]?.[1] ?? 0) > 1000;
        const reprojected = is3857 ? geom : (feature4326To3857(geom) as Polygon | MultiPolygon);
        env = normalizeToPolygon(reprojected);
      } catch { /* RPC envelope is invalid */ }
    }

    // Step 3: If no RPC envelope, create one by insetting the parcel by 6m (~20ft)
    if (!env && parcelPoly3857) {
      try {
        const inset = buffer(parcelPoly3857, -feetToMeters(20));
        if (inset.coordinates?.[0]?.length >= 4) {
          env = inset;
        }
      } catch { /* buffer failed */ }
    }

    // Step 4: CRITICAL — clip envelope to parcel boundary.
    // The envelope must NEVER extend beyond the parcel.
    if (env && parcelPoly3857) {
      try {
        const clipped = intersection(parcelPoly3857, env);
        const clippedPolys = polygons(clipped);
        if (clippedPolys.length > 0) {
          let best = clippedPolys[0];
          let bestArea = areaM2(best);
          for (let i = 1; i < clippedPolys.length; i++) {
            const a = areaM2(clippedPolys[i]);
            if (a > bestArea) { bestArea = a; best = clippedPolys[i]; }
          }
          return best;
        }
      } catch (err) {
        console.warn('[envelopeMeters] intersection failed, using buffer fallback:', err);
      }

      // Intersection failed — fall back to buffer(parcel, -6m)
      try {
        const inset = buffer(parcelPoly3857, -feetToMeters(20));
        if (inset.coordinates?.[0]?.length >= 4) {
          return inset;
        }
      } catch { /* buffer also failed */ }

      // Last resort: use the parcel polygon itself (no setbacks, but at least it's correct)
      return parcelPoly3857;
    }

    // If we have env but no parcel (shouldn't happen), return env
    if (env) return env;

    // No envelope at all
    return parcelPoly3857;
  }, [envelope, status, parcel?.geometry]);

  // Fallback = the envelope fetch SETTLED without a usable RPC envelope.
  // (While status is 'loading' the banner shows loading — previously this
  // flashed a misleading "fallback" banner during the ~600ms fetch.)
  const usingFallbackEnvelope = !!(envelopeMeters && status !== 'loading' && !(envelope && status === 'ready'));

  // Elements and envelope stay in EPSG:3857 meters — no feet conversion.
  // The canvas viewport fits to processedGeometry (also EPSG:3857 meters).

  const handleGenerate = useCallback(async (iterations?: unknown) => {
    if (!envelopeMeters) return;
    // Guard: button handlers pass the click event — only numbers count.
    const iters = typeof iterations === 'number' ? iterations : 50;
    planModeRef.current = 'mf';
    const ctx = ctxSettledRef.current;
    const zoningLabel = ctx && ctx !== 'pending' && ctx.zoningBase ? ctx.zoningBase : null;
    setPlanBasis(
      `Multifamily massing (${config.designParameters.buildingTypology})` +
      (zoningLabel ? ` — ${zoningLabel}` : ' — default assumptions') +
      (iters > 0 ? ' · SA-refined' : '')
    );
    // A generate replaces the layout — snapshot it so it's one undo step.
    if (currentBuildingsRef.current.length > 0) pushHistory();
    setIsGenerating(true);
    try {
      const parkingSpec = {
        stallW: feetToMeters(config.designParameters.parking.stallWidthFt),
        stallD: feetToMeters(config.designParameters.parking.stallDepthFt),
        aisleW: feetToMeters(config.designParameters.parking.aisleWidthFt),
        anglesDeg: [0, 60, 90]
      };

      // Use the optimizer for "Generate Plan" — it runs simulated annealing
      const result = await workerManager.optimizeSite(
        envelopeMeters,
        config.zoning,
        config.designParameters,
        parkingSpec,
        iters // 0 = instant constructive solve; >0 = SA refinement
      );

      // Feed best result into the plan output (already in EPSG:3857 meters)
      setPlanOutput(
        result.bestElements || [],
        result.bestMetrics || null
      );
      setViolations(result.bestViolations || []);
      trackBuildings(result.bestBuildings);

      // Surface the optimizer's best + ranked alternatives in the solve table.
      // (Replaces the deprecated legacy-planner "generateAlternatives" path.)
      const optimizerPlans = [
        { elements: result.bestElements || [], metrics: result.bestMetrics || null },
        ...(result.top3Alternatives || []).map(alt => ({
          elements: alt.elements || [],
          metrics: alt.metrics || null,
        })),
      ];
      const optimizerScores = [
        result.finalScore ?? 0,
        ...(result.top3Alternatives || []).map(alt => alt.score ?? 0),
      ];
      applyAlternatives(optimizerPlans as Parameters<typeof applyAlternatives>[0], optimizerScores);
      // Worker state is already synced with the optimizer's best buildings
      // (the OPTIMIZE handler sets siteState after optimize() returns)
      setSolverReady(true);
    } catch (error) {
      console.error('Failed to run optimizer:', error);
      // Fallback to basic initSite if optimizer fails
      try {
        const fallbackResult = await workerManager.initSite(envelopeMeters, config.zoning, undefined, {
          stallW: feetToMeters(config.designParameters.parking.stallWidthFt),
          stallD: feetToMeters(config.designParameters.parking.stallDepthFt),
          aisleW: feetToMeters(config.designParameters.parking.aisleWidthFt),
          anglesDeg: [0, 60, 90]
        }, typologyToBuildingType(config.designParameters.buildingTypology));
        setPlanOutput(fallbackResult.elements || [], fallbackResult.metrics || null);
        setViolations(fallbackResult.violations || []);
        setSolverReady(true);
      } catch (fallbackErr) {
        setSolverReady(false);
        setViolations([{
          code: 'worker',
          message: `Failed to generate plan: ${String(error)}`,
          severity: 'error'
        }]);
      }
    } finally {
      setIsGenerating(false);
    }
  }, [config, envelopeMeters, setPlanOutput, applyAlternatives, pushHistory, trackBuildings]);

  // Live re-solve: a fast, deterministic constructive solve (no annealing) run
  // when the user nudges parameter sliders, so the plan updates without clicking
  // "Generate". Quietly no-ops on failure — it's a preview, not a commit.
  const liveResolve = useCallback(async () => {
    if (!envelopeMeters) return;
    if (planModeRef.current === 'sf') return; // SF lot fits aren't massing-resolved
    try {
      const parkingSpec = {
        stallW: feetToMeters(config.designParameters.parking.stallWidthFt),
        stallD: feetToMeters(config.designParameters.parking.stallDepthFt),
        aisleW: feetToMeters(config.designParameters.parking.aisleWidthFt),
        anglesDeg: [0, 60, 90],
      };
      // 0 iterations → constructive solve: target-FAR layout + parking + metrics.
      const result = await workerManager.optimizeSite(
        envelopeMeters,
        config.zoning,
        config.designParameters,
        parkingSpec,
        0
      );
      setPlanOutput(result.bestElements || [], result.bestMetrics || null);
      setViolations(result.bestViolations || []);
      trackBuildings(result.bestBuildings);
      const plans = [
        { elements: result.bestElements || [], metrics: result.bestMetrics || null },
        ...(result.top3Alternatives || []).map(alt => ({
          elements: alt.elements || [],
          metrics: alt.metrics || null,
        })),
      ];
      const scores = [
        result.finalScore ?? 0,
        ...(result.top3Alternatives || []).map(alt => alt.score ?? 0),
      ];
      applyAlternatives(plans as Parameters<typeof applyAlternatives>[0], scores);
    } catch {
      /* live preview failure is non-fatal — the user can still click Generate */
    }
  }, [config, envelopeMeters, setPlanOutput, applyAlternatives, trackBuildings]);

  // ── Dynamic drag re-solve ────────────────────────────────────────────────
  // The Shell streams building updates on EVERY mouse move. We coalesce them
  // latest-wins and keep exactly one solve in flight, so the plan re-packs
  // around the drag at whatever rate the engine can actually deliver — the
  // TestFit "co-creation" feel — without ever queueing a backlog.
  type BuildingUpdate = {
    id: string;
    anchor: { x: number; y: number };
    rotationRad: number;
    widthFt: number;
    depthFt: number;
    floors?: number;
  };
  const updateInFlightRef = useRef(false);
  const pendingUpdateRef = useRef<BuildingUpdate | null>(null);

  const pumpBuildingUpdates = useCallback(() => {
    if (updateInFlightRef.current) return;
    const update = pendingUpdateRef.current;
    if (!update) return;
    pendingUpdateRef.current = null;
    updateInFlightRef.current = true;

    // Canvas coordinates are already in EPSG:3857 meters — pass directly to
    // worker. (The Shell field names say "Ft" but they carry meters.)
    workerManager
      .updateBuilding(update.id, {
        anchorX: update.anchor.x,
        anchorY: update.anchor.y,
        rotationRad: update.rotationRad,
        widthM: update.widthFt,
        depthM: update.depthFt,
        floors: update.floors,
      })
      .then(result => {
        setPlanOutput(result.elements || [], result.metrics || null);
        setViolations(result.violations || []);
        trackBuildings(result.buildings);
      })
      .catch(err => {
        console.error('Building update failed:', err);
        setViolations([{ code: 'worker', message: String(err), severity: 'error' }]);
      })
      .finally(() => {
        updateInFlightRef.current = false;
        pumpBuildingUpdates(); // drain whatever arrived while solving
      });
  }, [setPlanOutput]);

  const handleBuildingUpdate = useCallback(
    (update: BuildingUpdate, options?: { final?: boolean }) => {
      if (!envelopeMeters) return;
      // Snapshot once at the START of each gesture (first update after idle)
      // so a whole drag/rotate undoes in one step.
      if (!options?.final && !gestureActiveRef.current) {
        gestureActiveRef.current = true;
        pushHistory();
      }
      if (options?.final) {
        if (!gestureActiveRef.current) pushHistory(); // click-placed (no move phase)
        gestureActiveRef.current = false;
      }
      pendingUpdateRef.current = update; // latest-wins (the final release update is always last)
      pumpBuildingUpdates();
    },
    [envelopeMeters, pumpBuildingUpdates, pushHistory]
  );

  /** Undo/redo restore + real deletes: replay a building set through the worker. */
  const applyBuildingSet = useCallback(async (buildings: BuildingSpec[]) => {
    try {
      const result = await workerManager.setBuildings(buildings);
      setPlanOutput(result.elements || [], result.metrics || null);
      setViolations(result.violations || []);
      trackBuildings(result.buildings ?? buildings);
    } catch (err) {
      console.error('Building-set restore failed:', err);
      setViolations([{ code: 'worker', message: String(err), severity: 'error' }]);
    }
  }, [setPlanOutput, trackBuildings]);

  const undo = useCallback(() => {
    const prev = pastRef.current.pop();
    if (!prev) return;
    futureRef.current.push(structuredClone(currentBuildingsRef.current));
    setHistoryVersion(v => v + 1);
    void applyBuildingSet(prev);
  }, [applyBuildingSet]);

  const redo = useCallback(() => {
    const next = futureRef.current.pop();
    if (!next) return;
    pastRef.current.push(structuredClone(currentBuildingsRef.current));
    setHistoryVersion(v => v + 1);
    void applyBuildingSet(next);
  }, [applyBuildingSet]);

  const handleDeleteBuildings = useCallback((ids: string[]) => {
    const remaining = currentBuildingsRef.current.filter(b => !ids.includes(b.id));
    if (remaining.length === currentBuildingsRef.current.length) return;
    pushHistory();
    void applyBuildingSet(remaining);
  }, [applyBuildingSet, pushHistory]);

  // Ctrl/Cmd+Z undo, Ctrl/Cmd+Shift+Z or Ctrl/Cmd+Y redo
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (!(e.ctrlKey || e.metaKey)) return;
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
      const k = e.key.toLowerCase();
      if (k === 'z' && !e.shiftKey) {
        e.preventDefault();
        undo();
      } else if ((k === 'z' && e.shiftKey) || k === 'y') {
        e.preventDefault();
        redo();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [undo, redo]);

  /**
   * Ground the solver in the context engine's zoning values (once per
   * parcel+use): the FIRST auto-solve then runs on real setbacks/FAR/height
   * instead of hardcoded defaults. Fail-soft: no context → defaults stand.
   */
  const applyContextDefaults = useCallback(
    (ctx: DesignContext) => {
      const key = `${contextOgcFid}:${contextUse}`;
      if (appliedContextRef.current === key) return;
      appliedContextRef.current = key;
      const patch = contextToZoningPatch(ctx);
      if (Object.keys(patch).length === 0) return;
      updateConfig({ zoning: { ...config.zoning, ...patch } });
    },
    [contextOgcFid, contextUse, config.zoning, updateConfig]
  );

  /** Brief Phase 2: market-grounded SF lot fit, appended to the plan. */
  const handleGenerateLots = useCallback(async () => {
    planModeRef.current = 'sf';
    if (contextOgcFid == null) {
      setLotFitSummary('Lot fit needs a numeric parcel id.');
      return;
    }
    setIsGeneratingLots(true);
    try {
      const resp = await generateSfSitePlan(contextOgcFid);
      if (!resp) {
        setLotFitSummary('Lot generator unavailable — backend RPC not reachable.');
        return;
      }
      const { elements: generated, summary } = sfPlanToElements(resp);
      if (generated.length === 0) {
        setLotFitSummary('Generator returned no drawable lots for this parcel.');
        return;
      }
      // Additive per the brief: generated lots/footprints join the existing plan
      setPlanOutput([...elements, ...generated], metrics);
      const flagsNote = summary.flags.length > 0 ? ` · ⚠ ${summary.flags.join(', ')}` : '';
      setLotFitSummary(
        `${summary.lots} lots · lot target ${summary.targetLotSqft?.toLocaleString() ?? '—'} SF, ` +
        `footprint ${summary.targetFootprintSqft?.toLocaleString() ?? '—'} SF ` +
        `(${summary.targetSource ?? 'n/a'}) · confidence ${summary.confidence ?? 'n/a'}${flagsNote}`
      );
    } finally {
      setIsGeneratingLots(false);
    }
  }, [contextOgcFid, elements, metrics, setPlanOutput]);

  const handleAddBuilding = useCallback(async () => {
    if (!envelopeMeters) {
      setViolations([{
        code: 'envelope',
        message: 'Buildable envelope not available. Please wait for envelope to load.',
        severity: 'error'
      }]);
      return;
    }

    // If solver not ready, initialize it first
    if (!solverReady) {
      try {
        const parkingSpec = {
          stallW: feetToMeters(config.designParameters.parking.stallWidthFt),
          stallD: feetToMeters(config.designParameters.parking.stallDepthFt),
          aisleW: feetToMeters(config.designParameters.parking.aisleWidthFt),
          anglesDeg: [0, 60, 90] as number[]
        };
        const init = await workerManager.initSite(envelopeMeters, config.zoning, undefined, parkingSpec);
        setPlanOutput(init.elements || [], init.metrics || null);
        trackBuildings(init.buildings);
        setViolations(init.violations || []);
        setSolverReady(true);
      } catch (error) {
        console.error('Failed to initialize solver:', error);
        setViolations([{
          code: 'worker',
          message: `Failed to initialize solver: ${String(error)}`,
          severity: 'error'
        }]);
        setSolverReady(false);
        return;
      }
    }
    
    // Default dimensions in meters (convert from design defaults in feet)
    const defaultWidthM = feetToMeters(100);
    const defaultDepthM = feetToMeters(50);
    const defaultFloors = 3;

    // Place the new building at a LEGAL spot: flush along an open envelope
    // edge, avoiding existing buildings. The old envelope-centroid anchor sat
    // near/over the boundary on irregular parcels — and since user-added
    // buildings are pinned, the engine faithfully kept the bad spot.
    const existingFootprints = currentBuildingsRef.current.map(b => buildBuildingFootprint(b));
    const slot = placeBarsAlongEdges(envelopeMeters, {
      widthM: defaultWidthM,
      depthM: defaultDepthM,
      count: 1,
      avoidFootprints: existingFootprints,
    })[0];
    const centroid = calculatePolygonCentroid(envelopeMeters.coordinates[0]);
    const anchor = slot ? slot.anchor : { x: centroid[0], y: centroid[1] };
    const rotationRad = slot ? slot.rotationRad : 0;

    // Find next available building ID
    const existingIds = elements.filter(e => e.type === 'building').map(e => e.id);
    let buildingNum = 1;
    while (existingIds.includes(`building-${buildingNum}`)) {
      buildingNum++;
    }
    const newId = `building-${buildingNum}`;

    // handleBuildingUpdate now passes values directly to worker (already in meters)
    handleBuildingUpdate({
      id: newId,
      anchor,
      rotationRad,
      widthFt: defaultWidthM,   // actually meters — Shell field name is legacy
      depthFt: defaultDepthM,   // actually meters — Shell field name is legacy
      floors: defaultFloors
    }, { final: true });
  }, [envelopeMeters, elements, handleBuildingUpdate, solverReady, config, setPlanOutput]);

  const derivedInvestmentAnalysis = useMemo<InvestmentAnalysis | null>(() => {
    if (!metrics) return null;
    const gfa = metrics.totalBuiltSF || 0;
    if (gfa <= 0) return null;

    // Single source of truth for underwriting — the same engine the optimizer
    // scores with. When the plan metrics carry a (depth-aware) unit count, build
    // the mix from that exact count so the pro forma's revenue line agrees with
    // the "Units" figure on screen; otherwise fall back to the GFA heuristic.
    const siteAreaSqft = envelopeMeters ? correctedAreaM2(envelopeMeters) * 10.7639 : 0;
    const unitMix = metrics.totalUnits && metrics.totalUnits > 0
      ? generateUnitMixForCount(metrics.totalUnits)
      : generateDefaultUnitMix(gfa);
    const pf = computeProForma({
      totalGFASqft: gfa,
      siteAreaSqft,
      unitMix,
      surfaceStalls: metrics.stallsProvided ?? 0,
      structuredStalls: 0,
      landCost: parcel.parval ?? 0,
    });

    return {
      grossPotentialRent: pf.grossPotentialRent,
      vacancyLoss: pf.vacancyLoss,
      effectiveGrossIncome: pf.effectiveGrossIncome,
      operatingExpenses: pf.operatingExpenses,
      netOperatingIncome: pf.netOperatingIncome,
      totalDevelopmentCost: pf.totalDevelopmentCost,
      totalHardCosts: pf.totalHardCosts,
      softCosts: pf.softCosts,
      contingency: pf.contingency,
      financingCosts: pf.financingCosts,
      landCost: pf.landCost,
      yieldOnCost: pf.yieldOnCost,
      stabilizedValue: pf.stabilizedValue,
      profit: pf.profit,
      equityMultiple: pf.equityMultiple,
      cashOnCash: pf.cashOnCash,
      costPerUnit: pf.costPerUnit,
      costPerSF: pf.costPerSF,
      // Legacy aliases (kept for backward compat with older panels)
      totalInvestment: pf.totalDevelopmentCost,
      projectedRevenue: pf.grossPotentialRent,
      capRate: 0.055,
      // NOTE: a true IRR needs time-phased cash flows (a later phase). Until then
      // expose 0 rather than mislabeling unlevered yield-on-cost as IRR.
      irr: 0,
      paybackPeriod: pf.netOperatingIncome > 0 ? pf.totalDevelopmentCost / pf.netOperatingIncome : 0,
      riskAssessment: pf.yieldOnCost > 0.07 ? 'low' : pf.yieldOnCost > 0.05 ? 'medium' : 'high',
    };
  }, [metrics, envelopeMeters, parcel.parval]);

  useEffect(() => {
    setInvestmentAnalysis(derivedInvestmentAnalysis);
  }, [derivedInvestmentAnalysis]);

  // Reset auto-generation flag when parcel changes
  useEffect(() => {
    const currentId = parcel.ogc_fid ?? parcel.id ?? null;
    if (lastParcelIdRef.current !== currentId) {
      lastParcelIdRef.current = currentId;
      hasAutoGeneratedRef.current = false;
      setSolverReady(false);
      planModeRef.current = null;
      ctxSettledRef.current = 'pending';
      setPlanBasis(null);
    }
  }, [parcel.ogc_fid, parcel.id]);

  /** MF branch of the auto-plan (constructive, instant). */
  const autoPlanMf = useCallback((ctx: DesignContext | null) => {
    planModeRef.current = 'mf';
    handleGenerate(0).catch(() => undefined);
    // handleGenerate sets the basis label from the settled context
    void ctx;
  }, [handleGenerate]);

  /**
   * HBU-routed auto-plan: the context engine's regime decides WHAT gets
   * planned. civil/horizontal (single-family zoning) → market-grounded lot
   * fit, no multifamily parking apparatus; architectural/vertical → massing
   * engine (instant constructive solve; SA stays on the Generate button).
   */
  const autoPlan = useCallback((ctx: DesignContext | null) => {
    if (hasAutoGeneratedRef.current || !envelopeMeters || !hasValidGeometry) return;
    hasAutoGeneratedRef.current = true;
    if (ctx && isHorizontalRegime(ctx)) {
      planModeRef.current = 'sf';
      setPlanBasis(
        `Single-family lot fit — ${ctx.zoningBase ?? 'zoning'} as-of-right · lots sized from local comps`
      );
      handleGenerateLots().catch(() => undefined);
    } else {
      autoPlanMf(ctx);
    }
  }, [envelopeMeters, hasValidGeometry, handleGenerateLots, autoPlanMf]);

  const handleContextSettled = useCallback((ctx: DesignContext | null) => {
    ctxSettledRef.current = ctx;
    autoPlan(ctx);
  }, [autoPlan]);

  // Fallback: if the context engine hasn't settled ~2.5s after the envelope is
  // ready, don't block the user — plan with whatever we have (MF default).
  useEffect(() => {
    if (!hasValidGeometry || !envelopeMeters) return;
    if (hasAutoGeneratedRef.current) return;
    const timer = window.setTimeout(() => {
      autoPlan(ctxSettledRef.current === 'pending' ? null : ctxSettledRef.current);
    }, 2500);
    return () => window.clearTimeout(timer);
  }, [hasValidGeometry, envelopeMeters, autoPlan]);

  // Live re-solve when a design parameter changes (FAR, coverage, parking,
  // typology) — but only after the first plan exists. Debounced so dragging a
  // slider doesn't fire a solve per pixel. Reads the latest solverReady /
  // liveResolve from the fresh closure created on each parameter change.
  const liveResolveTimer = useRef<number | null>(null);
  useEffect(() => {
    if (!solverReady || !envelopeMeters) return;
    if (liveResolveTimer.current) window.clearTimeout(liveResolveTimer.current);
    liveResolveTimer.current = window.setTimeout(() => { liveResolve(); }, 350);
    return () => {
      if (liveResolveTimer.current) window.clearTimeout(liveResolveTimer.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [config.designParameters, config.zoning]);

  const plannerParcel = isValidParcel(parcel)
    ? parcel
    : createFallbackParcel(parcel.ogc_fid || parcel.id || 'unknown', parcel.sqft || 4356);

  // historyVersion re-renders this component whenever the undo stacks change
  const canUndo = historyVersion >= 0 && pastRef.current.length > 0;
  const canRedo = historyVersion >= 0 && futureRef.current.length > 0;

  return (
    <div className="h-full min-h-0 flex flex-col bg-gray-100">
      {/* Live KPI bar — always visible, ticks during drags/slider moves */}
      <div className="flex items-center justify-between gap-4 px-4 py-2 bg-white border-b border-gray-200 flex-shrink-0">
        <KpiStrip metrics={metrics} investment={investmentAnalysis} />
        <div className="flex items-center gap-2 flex-shrink-0">
        <div className="inline-flex rounded-lg border border-gray-200 overflow-hidden text-sm">
          <button
            onClick={undo}
            disabled={!canUndo}
            title="Undo (Ctrl+Z)"
            className="px-2.5 py-1.5 bg-white text-gray-600 hover:bg-gray-50 disabled:opacity-30 disabled:cursor-not-allowed"
          >
            <Undo2 className="w-4 h-4" />
          </button>
          <button
            onClick={redo}
            disabled={!canRedo}
            title="Redo (Ctrl+Shift+Z)"
            className="px-2.5 py-1.5 bg-white text-gray-600 hover:bg-gray-50 disabled:opacity-30 disabled:cursor-not-allowed border-l border-gray-200"
          >
            <Redo2 className="w-4 h-4" />
          </button>
        </div>
        <div className="inline-flex rounded-lg border border-gray-200 overflow-hidden text-sm flex-shrink-0">
          <button
            onClick={() => setViewMode('2d')}
            className={`px-3 py-1.5 ${viewMode === '2d' ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-50'}`}
          >
            2D Plan
          </button>
          <button
            onClick={() => setViewMode('3d')}
            className={`px-3 py-1.5 border-l border-gray-200 ${viewMode === '3d' ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-50'}`}
          >
            3D Massing
          </button>
        </div>
        </div>
      </div>

      {planBasis && (
        <div className="px-4 py-1.5 bg-white border-b border-gray-100 text-xs text-gray-600 flex-shrink-0">
          <span className="font-medium text-gray-700">Plan basis:</span> {planBasis}
        </div>
      )}

      <div className="flex-1 min-h-0 flex flex-col xl:flex-row gap-4 p-4 overflow-auto xl:overflow-hidden">
        <div className="w-full xl:w-80 flex-shrink-0 xl:min-h-0 xl:overflow-y-auto space-y-4">
          <ContextPanel
            ogcFid={contextOgcFid}
            use={contextUse}
            onUseChange={setContextUse}
            onContext={applyContextDefaults}
            onSettled={handleContextSettled}
          />
          <ParametersPanel
            parcel={parcel}
            config={config}
            onConfigChange={updateConfig}
            rpcMetrics={rpcMetrics}
            status={status}
            isGenerating={isGenerating}
            onGenerate={handleGenerate}
            onGenerateAlternatives={handleGenerate}
            onGenerateLots={handleGenerateLots}
            isGeneratingLots={isGeneratingLots}
            lotFitSummary={lotFitSummary}
            alternatives={alternatives}
            alternativeScores={solveScores}
            selectedSolveIndex={selectedSolveIndex}
            onSelectSolve={selectSolve}
            savedPlans={savedPlans}
            savedPlansLoading={savedPlansLoading}
            savedPlansError={savedPlansError}
            onSavePlan={handleSavePlan}
            onLoadPlan={handleLoadPlan}
            onDeletePlan={deletePlanFromDb}
            onToggleFavorite={togglePlanFavorite}
            currentElements={elements}
            currentMetrics={metrics}
            currentViolations={violations}
            currentInvestment={investmentAnalysis}
          />
        </div>

        <div className="flex-1 min-w-0 min-h-[420px] xl:min-h-0">
          {viewMode === '3d' ? (
            <SitePlannerErrorBoundary>
              <Massing3D elements={elements} />
            </SitePlannerErrorBoundary>
          ) : (
            <SitePlannerErrorBoundary>
              <EnterpriseSitePlanner
                parcel={plannerParcel}
                planElements={elements}
                metrics={metrics || undefined}
                selectedSolve={selectedSolve || undefined}
                parkingViz={{
                  angleDeg: metrics?.parkingAngleDeg ?? 0,
                  stallWidthFt: config.designParameters.parking.stallWidthFt,
                  stallDepthFt: config.designParameters.parking.stallDepthFt
                }}
                buildableEnvelope={envelopeMeters || undefined}
                edgeClassifications={edgeClassifications}
                setbacks={rpcMetrics?.setbacks}
                onBuildingUpdate={handleBuildingUpdate}
                onAddBuilding={handleAddBuilding}
                onDeleteBuildings={handleDeleteBuildings}
                envelopeStatus={status}
                envelopeError={envelopeError}
                usingFallbackEnvelope={usingFallbackEnvelope}
                onRetryEnvelope={() => {
                  // Force re-fetch by clearing the ref and triggering useEffect
                  // The hook will re-fetch when parcel.ogc_fid changes or ref is cleared
                  window.location.reload();
                }}
              />
            </SitePlannerErrorBoundary>
          )}
        </div>

        <div className="w-full xl:w-80 flex-shrink-0 xl:min-h-0 xl:overflow-y-auto">
          <ResultsPanel
            metrics={metrics}
            investmentAnalysis={investmentAnalysis}
            isGenerating={isGenerating}
            violations={violations}
            edgeClassifications={edgeClassifications}
            setbacks={rpcMetrics?.setbacks}
          />
        </div>
      </div>
    </div>
  );
};

export default SiteWorkspace;
